### ISSUE TITLE
DAG not found when there are multiple schedulers

### ISSUE THREAD

**Issue by cw75** [fluent-project/fluent#104]
When we have more than one scheduler, the scheduler will crash if it received a DAG call request from the client but the DAG info hasn't been gossiped to it yet.

**Comment by vsreekanti** [comment]
I think I already fixed this, but it might not be merged yet --- the simple fix is to just say that the DAG doesn't exist yet. We can also check the KVS to see if it exists.

**Comment by vsreekanti** [comment]
This was already fixed in #101: See [here](https://github.com/fluent-project/fluent/blob/master/functions/scheduler/server.py#L131).
