### ISSUE TITLE
AWS getting started depends on non namespaced env vars

### ISSUE THREAD

**Issue by Waterdrips** [fluent-project/fluent#108]
fluent/docs/getting-started-aws.md states that it requires NAME and KOPS... env vars 

These env vars could 
a) conflict with existing setups on a dev machine
b) If found without context they might not be identifiable to the code that uses them

Proposal:
Migrate these to a namespaced (and more descriptive) variable, say FLUENT_NAME or similar

**Comment by vsreekanti** [comment]
Closed by #116.
