### ISSUE TITLE
Proposal: Create Docker containers for initialising an AWS cluster

### ISSUE THREAD

**Issue by Waterdrips** [fluent-project/fluent#109]
Motivation:

- I dont want to have to install stuff locally if im only going to use it for this
- Portability - Other OS platforms can run the commands (Windows?) inside docker
- Becomes more robust - specific versions of libs can be installed and tested as a unit rather than having the developer have to manage and debug these

**Comment by vsreekanti** [comment]
Hi @Waterdrips, thanks for all of your suggestions and comments. You can find up-to-date Docker images for all the system components [here](https://hub.docker.com/u/fluentproject). These are the images used when creating a Kubernetes cluster. Let me know if this is what you were looking for.

**Comment by vsreekanti** [comment]
Closing this for now. Let me know if you have other questions, @Waterdrips.
