### ISSUE TITLE
Can Anna loss update when node failed before send merge request to other node？

### ISSUE THREAD

**Issue by swimmingsand** [fluent-project/fluent#110]
Anna is multi master system and need coordination-free merge function to implement replica consistency. 

Each Anna actor repeatedly checks for incoming requests for puts and gets from client proxies, serves those requests, and appends results to a local change set, which tracks the key-value pair updated within a period of time (the multicast epoch).

Now, during the epoch, if this node failed, Anna has any method to prevent loss of update？

**Comment by cw75** [comment]
Hello,

Thanks for the question. By default, each update (PUT) is acked when it is processed by one node, and so if this node fails before gossiping the update to other replicas, the update will be lost.

Persistence can be achieved via the `put_all` api that forces the PUT to be acked by all replicas before returning.

**Comment by swimmingsand** [comment]
Hello,
Thanks for you answer. 
After I read some code, I found gossiping period time is 10s by default.
```
// Define the gossip period (frequency)
#define PERIOD 10000000  // 10 seconds
```
During the period, only one replica's latest data can be seen by client, all other replica's data is not consistent with the replica which processed the PUT operation. This can be a problem for many application.

If client use put_all api, PUT performance can be a problem？

**Comment by cw75** [comment]
It is totally true that before the gossip, other replicas will serve stale versions to the clients, and there is actually a fundamental trade-off between staleness and performance in any coordination-free eventually consistent systems.

As you said, for certain applications, this staleness may not be tolerable. In this case we either have to reduce the gossip period (reduce the duration of staleness) or switch to a strongly consistent KVS (if the application cannot tolerate any staleness).

Interestingly, using `put_all` still introduces staleness as the PUT and GET are uncoordinated. `put_all` only increases the persistence of the updates.
