### ISSUE TITLE
[zeromqcpp] from 4.3.1, use recv taking a reference to message_t and recv_flags

### ISSUE THREAD

**Issue by authwork** [fluent-project/fluent#112]
Here is a problem about zeromqcpp.
In the laste version, we can see:
```
#ifdef ZMQ_CPP11
    ZMQ_DEPRECATED("from 4.3.1, use recv taking a reference to message_t and recv_flags")
#endif
    bool recv(message_t *msg_, int flags_
#ifndef ZMQ_CPP11
              = 0
#endif
    )
    {
        int nbytes = zmq_msg_recv(msg_->handle(), _handle, flags_);
        if (nbytes >= 0)
            return true;
        if (zmq_errno() == EAGAIN)
            return false;
        throw error_t();
    }
```
flags_ cannot be automaticlly set to be 0 when using "-std=c++11", and we need to pass 0 when calling recv.
However, in this way, the system cannot work right. It shows error like:
```
./build/kvs/client/cpp/terminate called after throwing an instance of 'zmq::error_t'
  what():  Operation cannot be accomplished in current state
```

I am now trying another solutions is to use an older version of zeromqcpp and will update here.

**Comment by authwork** [comment]
An older version of zeromqcpp will remove the compile issue, but the system still works incorrect.
My step likes following:
```
> ./scripts/start-kvs-local.sh n n
> ./build/kvs/client/cpp/flkvs-cli ./conf/kvs-config.yml
kvs> GET
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
terminate called after throwing an instance of 'zmq::error_t'
  what():  Operation cannot be accomplished in current state
```
By the way, we cannot find "./build/kvs/src/cli/flkvs-cli", I guess it may change to another location, i.e., "./build/kvs/client/cpp/flkvs-cli".

**Comment by vsreekanti** [comment]
Thanks for pointing this out, @authwork. It seems like this is an accidental misconfiguration in the latest version of ZMQ, as you can see [here](https://github.com/zeromq/cppzmq/pull/328). I explicitly set the ZMQ version to 4.2.3 on my local machine, and that seems to have fixed the issue. I'll make a PR, and we'll see if it fixes it in the Travis context as well.
