### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by kokizzu** [fluent-project/fluent#115]
this project not google/search-engine friendly (obviously to attract more contributor)

there's already a lot of project called `fluent` or `anna`

suggestion: `fluentkv` or `fluentanna`

**Comment by vsreekanti** [comment]
@kokizzu, thanks for pointing this out. In addition to being a common name, Fluent conflicts with the popular Ruby logging framework, [fluentd](https://github.com/fluent). We're working on coming up with a new name for the project but haven't quite figured one out yet. If you have any suggestions, we'd love to hear them!
