### ISSUE TITLE
Suggestion: move to DaemonSet deployments for tasks required on every node

### ISSUE THREAD

**Issue by Waterdrips** [fluent-project/fluent#118]

**Comment by Waterdrips** [comment]
Hi,

You mentioned at the Craft Conf talk that the deployments are not managed as a deamonset.
It might be good to deploy them in this way so you can guarantee every node gets 1 set of the application components.

Kubernetes docs on DaemonSets : https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

**Comment by vsreekanti** [comment]
Thanks for pointing this out, @Waterdrips. It looks like DaemonSets simplify a lot of the deployment challenges we've had. Thanks for pointing this out! I'm working on moving to this model right now. 😄
