### ISSUE TITLE
Suggestion: Use Horizontal Pod Autoscaler to manage cluster size

### ISSUE THREAD

**Issue by Waterdrips** [fluent-project/fluent#119]
Kubernetes contains a feature to auto-scale up/down the cluster based on defined metrics.
It might be worth exploring if this can be used (along with DaemonSets) to scale the cluster based on demand rather than using python scripts

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by vsreekanti** [comment]
Thanks for all the suggestions again, @Waterdrips. I'm not sure this one will work for our purposes for a couple reasons. 

1. According to the link you shared above, the horizontal pod autoscaler "... does not apply to objects that can’t be scaled, for example, DaemonSets.". 
2. Our policy for autoscaling relies on a combination of a variety of metrics that are mostly collected internally (e.g., key access frequencies, client-reported e2e request latencies, etc.), which the HPA doesn't seem to have an API for dealing with. 

That said, now that I'm moving to deploying application components with DaemonSets, the scaling operations become a lot easier -- we just need to change the size of the `kops` instance groups, and the DaemonSet takes care of the rest.

Closing this issue for now -- feel free to reopen if there's something I'm missing here!

**Comment by Waterdrips** [comment]
@vsreekanti - I was thinking of the cluster autoscaler - it wont work if deployments are moving to DaemonStets also.
