### ISSUE TITLE
A detailed document

### ISSUE THREAD

**Issue by yuinm** [fluent-project/fluent#122]
fluent and anna is  cool ，Is there a detailed document? 
It’s hard to learn without documentation.

**Comment by vsreekanti** [comment]
Hi @yuinm -- thanks for your note. What sort of detailed documents are you looking for? You can find some [getting started](https://github.com/fluent-project/fluent/blob/master/docs/index.md) docs in the repo. If there are other things you'd like more detail on, please let us know, and we'll try to add docs for those things.

**Comment by yuinm** [comment]
Thank you for your reply.
I want to know what the principle is.
And want to know how to compare with tbb.

**Comment by vsreekanti** [comment]
You can find a more detailed comparison with TBB in this [paper](http://db.cs.berkeley.edu/jmh/papers/anna_ieee18.pdf). We are working on another paper with the architecture of the system and will post it when we can.
