### ISSUE TITLE
fail to install dependencies on OSX

### ISSUE THREAD

**Issue by lemonlinger** [fluent-project/fluent#16]
./scripts/install-dependencies-osx.sh
Installing the following packages via homebrew:
	* autoconf
	* automake
	* libtool
	* build-essential
	* unzip
	* pkg-config
	* wget
Updating Homebrew...
Error: No available formula with the name "build-essential"
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
Error: No similarly named formulae found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
./scripts/install-dependencies-osx.sh: line 55: unexpected EOF while looking for matching `"'
./scripts/install-dependencies-osx.sh: line 56: syntax error: unexpected end of file

**Comment by vsreekanti** [comment]
Hi @lemonlinger, thanks for catching this. Can you please try again with the script [here](https://github.com/fluent-project/fluent/pull/17)? We'll wait to merge that PR until we hear from you (or someone else) that this works. 

It works locally for me, but I just want to make sure that  there aren't any hidden dependencies that are required.

**Comment by andyli029** [comment]
It works, but lcov has some problem:
```
You might be asked for your password to install lcov...
--2018-09-11 22:12:42--  http://downloads.sourceforge.net/ltp/lcov-.tar.gz
正在解析主机 downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
正在连接 downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2018-09-11 22:12:43 错误 404：Not Found。

./scripts/install-dependencies-osx.sh: line 52: cd: lcov-: No such file or directory
./scripts/install-dependencies-osx.sh: line 54: lcov: command not found
All dependencies installed!
```

**Comment by andyli029** [comment]
@cw75 https://github.com/andyli028/fluent/commit/1b2261dc81541cf2a185d3e6f9d73c0ba91730d0
the pr is not merged?
