### ISSUE TITLE
error while running the scrpit/build-all.sh

### ISSUE THREAD

**Issue by perry020** [fluent-project/fluent#27]
While running this script, some source files turn out error, and the message is : no member named 'cerr' in namespace 'std'
It only can be build if I add the #include \<iostream\> in these files
os : mac high sierra 10.13.6

**Comment by vsreekanti** [comment]
Hi @perry020, can you please let us know what compiler you were using, and what flags you passed to the script? Thanks!

**Comment by soarway** [comment]
[ 16%] No install step for 'zeromq'
[ 17%] Completed 'zeromq'
[ 17%] Built target zeromq
make: *** [all] Error 2

**Comment by cw75** [comment]
Hi @soarway, could you please let us know what operating system and compiler are you using? Thanks.

**Comment by cw75** [comment]
@soarway were you running with Debug mode or release mode? Did you pass any flag to `scrpit/build-all.sh`?

**Comment by soarway** [comment]
@cw75  Release  mode

**Comment by cw75** [comment]
@soarway there should be lines in the middle where it says certain error occurred (in addition to the `make: *** [all] Error 2`). Could you please let us know what these errors are? Thanks.

**Comment by cw75** [comment]
@soarway which compiler are you using? g++ or clang++?

**Comment by cw75** [comment]
@soarway have you run `./scripts/install-dependencies.sh`?
could you paste the output when running this script? Your Clang version looks a bit old, and I am not sure if the `libc++-dev libc++abi-dev` are installed

**Comment by soarway** [comment]
@cw75 
[root@aaz fluent-master]#  ./scripts/install-dependencies.sh g++
Detected that this is a Fedora-based distribution.
Setting compiler to g++...
Installing the following packages via yum:
        * autoconf
        * automake
        * libtool
        * build-essential 
        * make
All dependencies installed!

[root@az fluent-master]#  ./scripts/install-dependencies.sh
Detected that this is a Fedora-based distribution.
No compiler is specified. Default compiler is clang++.
We currently are unable to support clang++ installation on Fedora distributions.
[root@iaz fluent-master]# 


[root@i4z fluent-master]#  ./scripts/install-dependencies.sh clang++
Detected that this is a Fedora-based distribution.
Setting compiler to clang++...
We currently are unable to support clang++ installation on Fedora distributions.

I'm configuring G++，   But when compiling, the compiler is clang++.

**Comment by soarway** [comment]
@cw75        My os ： CentOS Linux release 7.5.1804 (Core)

**Comment by soarway** [comment]
@cw75 
[root@i4z fluent-master]# yum install gcc-c++ libstdc++-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package gcc-c++-4.8.5-28.el7_5.1.x86_64 already installed and latest version
Package libstdc++-devel-4.8.5-28.el7_5.1.x86_64 already installed and latest version
Nothing to do
[root@i4z fluent-master]# yum install gcc
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package gcc-4.8.5-28.el7_5.1.x86_64 already installed and latest version
Nothing to do

**Comment by cw75** [comment]
@soarway Could you run `./scripts/build-all.sh -g`?
the `-g` flag should set the compiler to g++

**Comment by soarway** [comment]
@cw75        Use g++， success。
[100%] Built target run_server_handler_tests  
Thanks  you！

**Comment by cw75** [comment]
👍
