### ISSUE TITLE
Debug mode fails to compile

### ISSUE THREAD

**Issue by cw75** [fluent-project/fluent#30]
I got `cannot find /usr/local/lib/clang/6.0.0/lib/linux/libclang_rt.profile-x86_64.a` when building the repo in "Debug" mode

**Comment by vsreekanti** [comment]
Well, Debug mode is how Travis compiles the project. 😄 I think you might have to pass in `-t` along with `-bDebug`, or it'll fail otherwise. Can you test that out for me? It might make sense to just collapse the two issues.

**Comment by cw75** [comment]
I ran with `./scripts/build-all.sh -j4 -bDebug -t` but got the same error :(

**Comment by vsreekanti** [comment]
Okay, we can debug tomorrow. It works on my laptop, on Travis, and on Ubuntu 16.04 and 14.04, so it must be a configuration / mismatched parameter issue.

**Comment by vsreekanti** [comment]
@cw75, can you post some more detail for this?
