### ISSUE TITLE
Fail to install dependencies on Centos7.2

### ISSUE THREAD

**Issue by huangll99** [fluent-project/fluent#46]
Detected that this is a Fedora-based distribution.

No compiler is specified. Default compiler is clang++.
We currently are unable to support clang++ installation on Fedora distributions.

**Comment by vsreekanti** [comment]
Hi @huangll99. I have been unable to build the project with `clang` on Fedora, so we have to default to using `gcc` instead. If you build with the `-g` flag, that will tell the script to use `gcc` instead of `clang`. Let me know if you have any other questions.

**Comment by huangll99** [comment]
> Hi @huangll99. I have been unable to build the project with `clang` on Fedora, so we have to default to using `gcc` instead. If you build with the `-g` flag, that will tell the script to use `gcc` instead of `clang`. Let me know if you have any other questions.

thanks a lot
