### ISSUE TITLE
how to integrate them in spring or spring boot？

### ISSUE THREAD

**Issue by chenziyi2018** [fluent-project/fluent#54]
do anyone know how to use them in spring or springboot or a website of tutorial? 
very thanks!

**Comment by ivanopagano** [comment]
What are you asking exactly?
This is not a java library if that's the question...

It's a datastore, similar to a database, so you run it as a service somewhere and talk to it via API calls, independently of the web-framework you might be using.

**Comment by cw75** [comment]
@chenziyi2018 we agree with @ivanopagano.
