### ISSUE TITLE
Broken FaaS API link in docs

### ISSUE THREAD

**Issue by haal** [fluent-project/fluent#67]
In [docs](https://github.com/fluent-project/fluent/blob/master/docs/index.md) link to function api is broken. Also, same on [getting started](https://github.com/fluent-project/fluent/blob/master/docs/getting-started.md)

**Comment by vsreekanti** [comment]
Hi @haal, thanks for pointing this out. That link shouldn't have been added yet, as we haven't written any documentation for the FaaS layer. We're still working on the details of the FaaS API, and if this is something you have opinions on, we'd love to chat more.

Sorry for the late response!

**Comment by haal** [comment]
Hi @vsreekanti, at the moment I just want to learn about this project and do some begginer excercises so this is how I found those links.
I am in learning phase so I am not sure that I can help anyhow with FaaS layer, but maybe with some introduction/getting started tutorials.
