### ISSUE TITLE
Random KVS server ZMQ error

### ISSUE THREAD

**Issue by vsreekanti** [fluent-project/fluent#85]
The KVS server crashes at random intervals with a ZMQ error saying that an operation cannot be accomplished in the current state of some socket. This isn't a super useful error message, but my hunch is that this has to do with one of the `REQ/REP` sockets (probably the `func_nodes_requester`?) trying to send a message before receiving one, but I'm not sure.

**Comment by cw75** [comment]
I think this is already resolved?
